# What is a Linear Equation
A **linear equation** is one where the unknowns (or variables) show up in a linear fashion - rather than being squared or under complex functions
<br><br>
**Linear**<br>
$2x + 3 = 0$<br>
$ay = c$<br>
$2u = 5$<br><br>
**Nonlinear**<br>
$2x^{2} + 3 = 0$<br>
$a\sqrt{y} = c$<br>
$2\textrm{ ln }u = 5$<br>


In [1]:
import numpy as np
from numpy.linalg import solve

In [2]:
A =np.array([[1.0, 1.0, 1.0],
     [0.04, 0.54, 0.26],
     [0.93, 0.24, 0.0]])
b =np.array([10.0, 2.0, 6.0])

In [3]:
print('A =', A)
print('b=', b)

A = [[1.   1.   1.  ]
 [0.04 0.54 0.26]
 [0.93 0.24 0.  ]]
b= [10.  2.  6.]


In [4]:
x = solve(A,b)
print(x)

[5.82375479 2.43295019 1.74329502]


Using inverse

In [16]:
from numpy.linalg import inv
Ainv = inv(A)

In [17]:
Ainv

array([[ 0.19923372, -0.76628352,  0.89399745],
       [-0.77203065,  2.96934866,  0.70242656],
       [ 1.57279693, -2.20306513, -1.59642401]])

In [22]:
x = b @ Ainv #@ symbol is equivalent with the dot product
print(x)

[  9.88505747 -14.94252874   0.76628352]


In [23]:
x = Ainv @ b
print(x)

[5.82375479 2.43295019 1.74329502]


In [24]:
Ainv.dot(b)

array([5.82375479, 2.43295019, 1.74329502])

## Solution method
$$\Large\Big[ A \Big]x = b$$
<br>
### Direct methods
General approach to solving an arbitrary system of linear equatioins. No iteration involved

### Iterative methods
Effective and much cheaper for sparse matrices (plenty of zeros in the matrix)

## Direct methods
- **Gaussian Elimination**
    - Algoritm to solve sytems of linear equations
    - Basically a methodic approach to solving equations 'by hand' 
    - Cost scales as $n^{3}$ where $n$ is the number of equations
- **LU Factorization**
    - Useful when you need to solve Ax=b for different b but same A
    - L -Lower diagonal matrix, U -Upper diagonal matrix
    - Determining L, U is "expensive", but solving the resulting system is simple
- **TDMA/PDMA**
    - Efficient direct solution methods for tridiagonal and pentadiagonal matrices
- **Fast FFT Solvers**
    - Efficient direct solution methods for periodic problems